### ISSUE TITLE
Add support for kubeconfig (CLI) integration

### ISSUE THREAD

**Issue by jcogilvie** [Noovolari/leapp#170]
**Is your feature request related to a problem? Please describe.**
I am a user of kubernetes and of `kubectl` and `eks`.  At present, `kubectl` references the aws binary for authentication, which expects certain named profiles to exist based on my `kubeconfig` file.  

Without `Leapp` installed, kubectl finds the profile and delegates to the `aws` binary which correctly prompts me for MFA and then works.  

With `Leapp` installed, I need to pre-authenticate the session in `Leapp` or else the profile is not found.  This represents a usability regression from the default `awscli` case.  

**Describe the solution you'd like**
Instead of kubectl directly asking AWS, there should be a way for kubectl to ask Leapp.  

It appears that a kubeconfig file (specifically one generated by `aws eks ...`) specifies how authentication is done by referencing the `aws` binary:

```
- name: arn:aws:eks:us-east-1:...:cluster/some-cluster-name
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - --region
      - us-east-1
      - eks
      - get-token
      - --cluster-name
      - some-cluster-name
      command: aws
      env:
      - name: AWS_PROFILE
        value: an-aws-config-profile
      interactiveMode: IfAvailable
      provideClusterInfo: false
```

It seems like integration could be achieved with a rewrite of the kubeconfig file to call `Leapp` on the command line rather than `aws`.  

So, Leapp needs to: 

1) provide such command line functionality as necessary for this integration (including a way to prompt me for MFA tokens when the integration is called, either in the terminal session or in a GUI prompt)
2) provide documentation for how to rewrite kubeconfig to support the use case

**Describe alternatives you've considered**
An alternative would be to keep the named profiles in the aws config to retain the existing awscli functionality, but this presents challenges with spawning an MFA prompt when necessary.  

I also imagined a case where Leapp could parse a kubeconfig file like the one above and rewrite it, but that seems out of scope for an app like this as it's kubernetes-specific.

**Comment by ericvilla** [comment]
Hi @jcogilvie,

looking at the [docs](https://docs.aws.amazon.com/eks/latest/userguide/create-kubeconfig.html), `aws eks get-token` or `aws-iam-authenticator` rely on credentials provided by default AWS credential provider chain, unless you specify AWS_PROFILE env variable in kubeconfig file.

As far as now, I think your configuration should work by setting AWS_PROFILE env variable to the profile you defined inside Leapp. Leapp provides a `default` AWS Named Profile that can be associated with the sessions. You can add another AWS Named Profile and reference it from the kubeconfig file.

> With Leapp installed, I need to pre-authenticate the session in Leapp or else the profile is not found. This represents a usability regression from the default awscli case.

If I understood what you mean, you'd like a way to generate credentials "on-demand" when you issue kubectl commands.
As @pethron stated, sourcing credentials from an external process could be the best fit for this need. We have an [issue](https://github.com/Noovolari/leapp-daemon/issues/20) open about this topic, in addition to the previously linked discussion.

**Comment by jcogilvie** [comment]
> If I understood what you mean, you'd like a way to generate credentials "on-demand" when you issue kubectl commands.
As @pethron stated, sourcing credentials from an external process could be the best fit for this need. We have an issue open about this topic, in addition to the previously linked discussion.

This sounds promising as a direction for development.

The CLI hook you're looking for might be as simple as inserting yourselves in the config file and proxying the call to `aws eks` underneath:

```
- name: arn:aws:eks:us-east-1:...:cluster/some-cluster-name
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - --whatever-args-are-necessary-to-get-an-eks-token
      command: leapp   # a leapp CLI executable
      env:
      - name: AWS_PROFILE
        value: an-aws-config-profile
      interactiveMode: IfAvailable
      provideClusterInfo: false
```
