### ISSUE TITLE
Enable *Cask* autoupdate 

### ISSUE THREAD

**Issue by andreacavagna01** [Noovolari/leapp#192]
**Is your feature request related to a problem? Please describe.**
Autoupdate brew cask formula by following this documentation:
https://docs.brew.sh/Cask-Cookbook

This in order to modify this formula 

https://github.com/Homebrew/homebrew-cask/edit/master/Casks/leapp.rb

making the formula version agnostic and enabling Autoupdate checks and download via Brew

**Comment by nitrocode** [comment]
Doesn't the liveupdate only allowing running `brew bump-cask-pr leapp --version=xyz` ?

formula link https://github.com/Homebrew/homebrew-cask/blob/master/Casks/leapp.rb

I think it would be better to setup a github action to bump it up

* https://github.com/marketplace/actions/bump-homebrew-formula
* https://github.com/marketplace/actions/homebrew-cask-bumper

Maybe something like this would work ?

```yaml
on:
  push:
    tags: 'v*'

jobs:
  homebrew:
    name: Bump Homebrew formula
    runs-on: ubuntu-latest
    steps:
      - uses: mislav/bump-homebrew-formula-action@v1
        with:
          # A PR will be sent to github.com/Homebrew/homebrew-cask to update this formula:
          formula-name: leapp
          formula-path: Casks/leapp.rb
          homebrew-tap: Homebrew/homebrew-cask
        env:
          COMMITTER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
